# Added due to required but conditional checks
# Read more: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: 'Anikage checks'
on:
  pull_request:
    paths-ignore:
      - "bin/**"
      - "src/**"
      - "server/**"
jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify core files"'
