name: 'Anikage version check'
on:
  pull_request:
    paths: 
      - "package.json"
      
jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: check version bump
      run: git diff origin/master | grep version || echo "Version check passed"
